name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  pod-lint:
    name: Pod Lint
    runs-on: macOS-15
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.1'
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Select Xcode Version
        run: sudo xcode-select --switch /Applications/Xcode_16.4.app/Contents/Developer
      - name: Bundle Install
        run: bundle install
      - name: Lint Podspec
        run: bundle exec pod lib lint --verbose --fail-fast
  tests:
    name: Test
    runs-on: macOS-15
    strategy:
      fail-fast: false
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.1'
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Bundle Install
        run: bundle install
      - name: Select Xcode Version
        run: sudo xcode-select --switch /Applications/Xcode_16.4.app/Contents/Developer
      - name: Run Tests
        run: xcodebuild -project Relativity.xcodeproj -scheme Relativity -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14" -configuration Debug -PBXBuildsContinueAfterErrors=0 build test
